package main.java.com.ha.sdk.inner;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : FaceRecoDef.h:199</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DebugImageInfo extends Structure {
	/** \u93c3\u5815\u68ff\u93b4\ufffd \u7ec9\ufffd */
	public int timeStamp_s;
	/** \u93c3\u5815\u68ff\u93b4\ufffd \u5bf0\ue1bc\ue6fe */
	public int timeStamp_u;
	/** \u59e3\u65bf\ue1ee\u7f01\u64b4\u7049\u951b\ufffd0\u951b\u6c2d\u6e6d\u59e3\u65bf\ue1ee\u9286\ufffd-1\u951b\u6c2d\u762e\u7035\u7470\u3051\u7490\u30e3\ufffd\ufffd1\u951b\u6c2d\u762e\u7035\u89c4\u579a\u9354\ufffd */
	public int matched;
	/** \u59e3\u65bf\ue1ee\u9352\u55d8\u669f */
	public int matchScore;
	/**
	 * \u59e3\u65bf\ue1ee\u6d93\u5a44\u6b91\u6d5c\u54c4\u61b3id\u951b\u5baeatched\u7edb\u5909\u7c2c1\u93c3\u8235\u6e41\u93c1\ufffd<br>
	 * C type : char[20]
	 */
	public byte[] faceId = new byte[20];
	/** \u748b\u51ad\u762f\u9365\u60e7\u511a\u93c1\u4f34\u567a\u951b\u5c7e\u6e36\u6fb6\u0444\u656e\u93b8\ufffd6\u5bee\u72b2\u6d58\u934d\ufffd */
	public int imageNum;
	/**
	 * \u748b\u51ad\u762f\u9365\u60e7\u511a\u6dc7\u2103\u4f05<br>
	 * C type : DebugImage[6]
	 */
	public DebugImage[] debugImage = new DebugImage[6];
	public DebugImageInfo() {
		super();
	}
	protected List<String>getFieldOrder() {
		return Arrays.asList("timeStamp_s", "timeStamp_u", "matched", "matchScore", "faceId", "imageNum", "debugImage");
	}
	/**
	 * @param timeStamp_s \u93c3\u5815\u68ff\u93b4\ufffd \u7ec9\ufffd<br>
	 * @param timeStamp_u \u93c3\u5815\u68ff\u93b4\ufffd \u5bf0\ue1bc\ue6fe<br>
	 * @param matched \u59e3\u65bf\ue1ee\u7f01\u64b4\u7049\u951b\ufffd0\u951b\u6c2d\u6e6d\u59e3\u65bf\ue1ee\u9286\ufffd-1\u951b\u6c2d\u762e\u7035\u7470\u3051\u7490\u30e3\ufffd\ufffd1\u951b\u6c2d\u762e\u7035\u89c4\u579a\u9354\ufffd<br>
	 * @param matchScore \u59e3\u65bf\ue1ee\u9352\u55d8\u669f<br>
	 * @param faceId \u59e3\u65bf\ue1ee\u6d93\u5a44\u6b91\u6d5c\u54c4\u61b3id\u951b\u5baeatched\u7edb\u5909\u7c2c1\u93c3\u8235\u6e41\u93c1\ufffd<br>
	 * C type : char[20]<br>
	 * @param imageNum \u748b\u51ad\u762f\u9365\u60e7\u511a\u93c1\u4f34\u567a\u951b\u5c7e\u6e36\u6fb6\u0444\u656e\u93b8\ufffd6\u5bee\u72b2\u6d58\u934d\ufffd<br>
	 * @param debugImage \u748b\u51ad\u762f\u9365\u60e7\u511a\u6dc7\u2103\u4f05<br>
	 * C type : DebugImage[6]
	 */
	public DebugImageInfo(int timeStamp_s, int timeStamp_u, int matched, int matchScore, byte faceId[], int imageNum, DebugImage debugImage[]) {
		super();
		this.timeStamp_s = timeStamp_s;
		this.timeStamp_u = timeStamp_u;
		this.matched = matched;
		this.matchScore = matchScore;
		if ((faceId.length != this.faceId.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.faceId = faceId;
		this.imageNum = imageNum;
		if ((debugImage.length != this.debugImage.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.debugImage = debugImage;
	}
	public static class ByReference extends DebugImageInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends DebugImageInfo implements Structure.ByValue {
		
	};
}
