package main.java.com.ha.sdk.inner;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : FaceRecoDef.h:183</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FaceDelProgressInfo extends Structure {
	/** \u9352\u72bb\u6ace\u9428\u52ed\u90af\u8930\u66df\ufffd\u7ed8\u669f */
	public int delCount;
	/** \u8930\u64b3\u58a0\u9352\u72bb\u6ace\u7ed7\ue100\u5691\u93c9\uff04\u90af\u8930\ufffd */
	public int curDelNo;
	/**
	 * \u8930\u64b3\u58a0\u9352\u72bb\u6ace\u9428\u52ea\u6c49\u935b\u696dD<br>
	 * C type : char[20]
	 */
	public byte[] faceId = new byte[20];
	public FaceDelProgressInfo() {
		super();
	}
	protected List<String>getFieldOrder() {
		return Arrays.asList("delCount", "curDelNo", "faceId");
	}
	/**
	 * @param delCount \u9352\u72bb\u6ace\u9428\u52ed\u90af\u8930\u66df\ufffd\u7ed8\u669f<br>
	 * @param curDelNo \u8930\u64b3\u58a0\u9352\u72bb\u6ace\u7ed7\ue100\u5691\u93c9\uff04\u90af\u8930\ufffd<br>
	 * @param faceId \u8930\u64b3\u58a0\u9352\u72bb\u6ace\u9428\u52ea\u6c49\u935b\u696dD<br>
	 * C type : char[20]
	 */
	public FaceDelProgressInfo(int delCount, int curDelNo, byte faceId[]) {
		super();
		this.delCount = delCount;
		this.curDelNo = curDelNo;
		if ((faceId.length != this.faceId.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.faceId = faceId;
	}
	public static class ByReference extends FaceDelProgressInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends FaceDelProgressInfo implements Structure.ByValue {
		
	};
}
