package main.java.com.ha.sdk.inner;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.FloatByReference;
import java.util.Arrays;
import java.util.List;
/**
 * \u6d5c\u9e3f\u52af\u93cc\u30e8\ue1d7\u9365\u70b6\u769f\u6769\u65bf\u6d16<br>
 * <i>native declaration : FaceRecoDef.h:105</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class QueryFaceInfo extends Structure {
	/** \u93cc\u30e8\ue1d7\u9428\u52ee\ue757\u9479\u8336\ue187\u8930\u66df\ufffd\u5a5a\u567a */
	public int record_count;
	/** \u8930\u64b3\u58a0\u93c0\u8dfa\u57cc\u9428\u52ee\ue187\u8930\u66de\u7c2d\u9359\ufffd */
	public int record_no;
	/**
	 * \u6d5c\u54c4\u61b3ID<br>
	 * C type : char[20]
	 */
	public byte[] personID = new byte[20];
	/**
	 * \u6fee\u64b3\u6095<br>
	 * C type : char[16]
	 */
	public byte[] personName = new byte[16];
	/** \u6d5c\u54c4\u61b3\u7459\u6395\u58ca 0\u951b\u6c2d\u6ad8\u95ab\u6c2b\u6c49\u935b\u6a38\ufffd\ufffd 1\u951b\u6c31\u6ae7\u935a\u5d85\u5d1f\u6d5c\u54c4\u61b3\u9286\ufffd 2\u951b\u6c36\u7ca6\u935a\u5d85\u5d1f\u6d5c\u54c4\u61b3\u9286\ufffd -1\u951b\u6c2d\u588d\u93c8\u5909\u6c49\u935b\u6a38\ufffd\ufffd */
	public int role;
	/** \u8930\u64b3\u58a0id\u9428\u52ed\u58d2\u5bf0\u4f79\u669f\u93ac\u5a5a\u567a */
	public short feature_count;
	/** \u6d5c\u9e3f\u52af\u9417\u7470\u7ddb\u93c1\u7248\u5d41\u95c0\u57ae\u5bb3 */
	public short feature_size;
	/**
	 * \u6d5c\u9e3f\u52af\u9417\u7470\u7ddb\u93c1\u7248\u5d41\u951b\u5c7e\u5bdc\u6924\u54c4\u7c2d\u93ba\u6391\u57aa\u93b5\ufffd\u93c8\u590c\u58d2\u5bf0\u4f79\u669f\u93b9\ufffd featureSize*feature_count<br>
	 * C type : float*
	 */
	public FloatByReference feature;
	/** \u59af\u2103\u6f98\u9365\u60e7\u511a\u93c1\u4f34\u567a */
	public int imgNum;
	/**
	 * \u9365\u60e7\u511a\u6fb6\u0443\u76ac\u951b\u5ba8mgSize[i]\u6d93\u8679\ue0c7i\u5bee\u72b2\u6d58\u9417\u56e9\u6b91\u6fb6\u0443\u76ac<br>
	 * C type : int[5]
	 */
	public int[] imgSize = new int[5];
	/**
	 * \u9365\u60e7\u511a\u93cd\u714e\u7d21,imgFmt[i]\u6d93\u8679\ue0c7i\u5bee\u72b2\u6d58\u9417\u56e9\u6b91\u93cd\u714e\u7d21<br>
	 * C type : char[5][4]
	 */
	public byte[] imgFmt = new byte[((5) * (4))];
	/**
	 * imgBuff[i]\u6d63\u5d87\ue0c7i\u5bee\u72b2\u6d58\u9417\u56e9\u7cb0\u93c1\u7248\u5d41\u68e3\u6827\u6e74\u9367\ufffd<br>
	 * C type : unsigned char*[5]
	 */
	public Pointer[] imgBuff = new Pointer[5];
	/** \u95ca\ufe3d\u7274\u95c2\u3127\ue6e6\u9357\u2033\u5f7f */
	public int wgCardNO;
	/** \u93b4\ue045\ue11b\u93c3\u5815\u68ff\u951b\u5c83\ue1da\u6d5c\u54c4\u61b3\u6dc7\u2103\u4f05\u9366\u3128\ue1da\u93c3\u5815\u68ff\u9350\u546e\u6e41\u93c1\ufffd,\u6d60\ufffd1970\u9a9e\ufffd1\u93c8\ufffd1\u93c3\ufffd0\u93c3\ufffd0\u9352\ufffd0\u7ec9\u6391\u57cc\u93b4\ue045\ue11b\u93c3\u5815\u68ff\u9428\u52ed\ue757\u93c1\u5e2e\u7d190xFFFFFFFF\u741b\u3127\u305a\u59d8\u9550\u7b99\u93c8\u590b\u6665\u951b\ufffd0\u741b\u3127\u305a\u59d8\u9550\u7b99\u6fb6\u8fa8\u6665\u951b\ufffd */
	public int effectTime;
	public QueryFaceInfo() {
		super();
	}
	protected List<String>getFieldOrder() {
		return Arrays.asList("record_count", "record_no", "personID", "personName", "role", "feature_count", "feature_size", "feature", "imgNum", "imgSize", "imgFmt", "imgBuff", "wgCardNO", "effectTime");
	}
	public static class ByReference extends QueryFaceInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends QueryFaceInfo implements Structure.ByValue {
		
	};
}
