package main.java.com.ha.sdk.inner;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u6d5c\u9e3f\u52af\u93cc\u30e8\ue1d7\u6769\u65bf\u6d16<br>
 * <i>native declaration : FaceRecoDef.h:92</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class QueryFaceFlags extends Structure {
	/**
	 * \u6d5c\u54c4\u61b3ID<br>
	 * C type : char[20]
	 */
	public byte[] personID = new byte[20];
	/**
	 * \u6fee\u64b3\u6095<br>
	 * C type : char[16]
	 */
	public byte[] personName = new byte[16];
	/** \u6d5c\u9e3f\u52af\u9417\u7470\u7ddb\u93c1\u7248\u5d41\u6fb6\u0443\u76ac */
	public int featureSize;
	/**
	 * \u6d5c\u9e3f\u52af\u9417\u7470\u7ddb\u93c1\u7248\u5d41<br>
	 * C type : float[2048]
	 */
	public float[] feature = new float[2048];
	/** \u9365\u60e7\u511a\u93c1\u626e\u6d30 */
	public int imgNum;
	/** \u9365\u60e7\u511a\u6fb6\u0443\u76ac */
	public int imgSize;
	/**
	 * \u9365\u60e7\u511a\u93c1\u7248\u5d41<br>
	 * C type : unsigned char[10240]
	 */
	public byte[] img = new byte[10240];
	/** C type : char[16] */
	public byte[] resv = new byte[16];
	public QueryFaceFlags() {
		super();
	}
	protected List<String>getFieldOrder() {
		return Arrays.asList("personID", "personName", "featureSize", "feature", "imgNum", "imgSize", "img", "resv");
	}
	/**
	 * @param personID \u6d5c\u54c4\u61b3ID<br>
	 * C type : char[20]<br>
	 * @param personName \u6fee\u64b3\u6095<br>
	 * C type : char[16]<br>
	 * @param featureSize \u6d5c\u9e3f\u52af\u9417\u7470\u7ddb\u93c1\u7248\u5d41\u6fb6\u0443\u76ac<br>
	 * @param feature \u6d5c\u9e3f\u52af\u9417\u7470\u7ddb\u93c1\u7248\u5d41<br>
	 * C type : float[2048]<br>
	 * @param imgNum \u9365\u60e7\u511a\u93c1\u626e\u6d30<br>
	 * @param imgSize \u9365\u60e7\u511a\u6fb6\u0443\u76ac<br>
	 * @param img \u9365\u60e7\u511a\u93c1\u7248\u5d41<br>
	 * C type : unsigned char[10240]<br>
	 * @param resv C type : char[16]
	 */
	public QueryFaceFlags(byte personID[], byte personName[], int featureSize, float feature[], int imgNum, int imgSize, byte img[], byte resv[]) {
		super();
		if ((personID.length != this.personID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.personID = personID;
		if ((personName.length != this.personName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.personName = personName;
		this.featureSize = featureSize;
		if ((feature.length != this.feature.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.feature = feature;
		this.imgNum = imgNum;
		this.imgSize = imgSize;
		if ((img.length != this.img.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.img = img;
		if ((resv.length != this.resv.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.resv = resv;
	}
	public static class ByReference extends QueryFaceFlags implements Structure.ByReference {
		
	};
	public static class ByValue extends QueryFaceFlags implements Structure.ByValue {
		
	};
}
