package main.java.com.ha.sdk.inner;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u7eef\u8364\u7cba\u9417\u581f\u6e70\u6dc7\u2103\u4f05<br>
 * <i>native declaration : FaceRecoDef.h:143</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SystemVersionInfo extends Structure {
	/**
	 * \u7481\u60e7\ue62c\u6434\u5fd3\u57aa\u9359\ufffd<br>
	 * C type : char[32]
	 */
	public byte[] dev_id = new byte[32];
	/**
	 * \u9357\u5fda\ue185\u9417\u581f\u6e70<br>
	 * C type : char[8]
	 */
	public byte[] protocol_ver = new byte[8];
	/**
	 * \u9365\u8f70\u6b22\u9417\u581f\u6e70<br>
	 * C type : char[16]
	 */
	public byte[] firmware_ver = new byte[16];
	/**
	 * \u6434\u65c2\u6564\u7ecb\u5b2a\u7c2d\u9417\u581f\u6e70<br>
	 * C type : char[8]
	 */
	public byte[] code_ver = new byte[8];
	/**
	 * \u6434\u65c2\u6564\u7f02\u682c\u7627\u93c3\u5815\u68ff<br>
	 * C type : char[20]
	 */
	public byte[] build_time = new byte[20];
	/**
	 * \u6dc7\u6fc8\u6680<br>
	 * C type : char[16]
	 */
	public byte[] resv = new byte[16];
	/**
	 * \u7eef\u8364\u7cba\u7eeb\u8bf2\u7037<br>
	 * C type : char[16]
	 */
	public byte[] systemp_type = new byte[16];
	/**
	 * \u7ead\ue0ff\u6b22\u9a9e\u51b2\u5f74<br>
	 * C type : char[16]
	 */
	public byte[] plateform = new byte[16];
	/**
	 * \u6d7c\u72b3\u5285\u9363\u3125\u7037\u9359\ufffd<br>
	 * C type : char[16]
	 */
	public byte[] sensor_type = new byte[16];
	/**
	 * \u7ee0\u6941\u7876\u9417\u581f\u6e70<br>
	 * C type : char[16]
	 */
	public byte[] algorithm_ver = new byte[16];
	/**
	 * \u93c8\ufffd\u6d63\u5dd7dk\u9417\u581f\u6e70<br>
	 * C type : char[16]
	 */
	public byte[] min_sdk_ver = new byte[16];
	/** \u93c8\ufffd\u6d63\u5ea1\ue179\u93b4\u98ce\ue06c\u9417\u581f\u6e70 */
	public int min_client_ver;
	public SystemVersionInfo() {
		super();
	}
	protected List<String>getFieldOrder() {
		return Arrays.asList("dev_id", "protocol_ver", "firmware_ver", "code_ver", "build_time", "resv", "systemp_type", "plateform", "sensor_type", "algorithm_ver", "min_sdk_ver", "min_client_ver");
	}
	public static class ByReference extends SystemVersionInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends SystemVersionInfo implements Structure.ByValue {
		
	};
}
